source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction

" Inserito da MauAGA per non creare i file di backup
"
set nobackup
set nowritebackup

" Eliminare gli undo file
set noundofile
"reserve current indent on new lines
set autoindent
" make backspaces delete sensibly
set backspace=indent,eol,start
" indentation levels every four columns
set tabstop=8
" convert all tabs to space
set expandtab
" indent/outdent by four columns
set shiftwidth=8
" indent/outdent to nearest tabstops
set shiftround
" syntax hilighting in vim
syntax on
" Inserire il numero di linea
set number

"
" Mettere il file dei colori grouvbox in vimfiles directory, vedere direcotry
" presente quì.
"
set background=dark
colorscheme gruvbox
set mouse=a
set ruler
set laststatus=2
set colorcolumn=80
